dist: trusty
sudo: false
language: python # for mkdocs
python:
  - 2.7
branches:
  only:
    - master
    # tags
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
before_install:
  # Lock dependencies for branch builds
  - |
    if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      export REQUIREMENTS_FILE=requirements.lock
    else
      export REQUIREMENTS_FILE=requirements.txt
    fi
install:
  - pip install -r "$REQUIREMENTS_FILE" -r dev-requirements.txt
  # Markdown linter
  - gem install mdl --bindir ~/.local/bin
  # Dirty hack for what seems like a bug in linkchecker
  - |
    find "$VIRTUAL_ENV" -regex '.*/linkcheck/__init__.py' -print0 | \
      xargs -0 sed -i -e "s/requests.__version__ <= '2.2.0'/map(int, requests.__version__.split('.')) <= [2, 2, 0]/"
  - python -m mkdocs --version
  - linkchecker --version
  - html5validator --version
  - ~/.local/bin/mdl --version

script:
  - python -m mkdocs build
  - bash ./misc/lint.sh md
  - bash ./misc/lint.sh html
  - bash ./misc/lint.sh links

after_script:
  # Kill mkdocs server if it's still running
  - bash ./misc/lint.sh kill

notifications:
  slack:
    rooms:
      secure: m+EwYesnSFJxJbwPI890FiXlWl/EaqKYNMDNE/Ti4vlsFTNQOHuYFdj6vihaGn53E3+aWaRnQ9jFJNXFyPab+LyeYErGssuhuN+QFVAGvACXtl54zYspNIx+zk6gN5mjX9vsP15K/XJi+YTX25zk9lyN6WlMdPvoW9cQqpMLxYyCG92aVfpHdsax3iocDWpQQBv0G1CWHGTyz2bcwFGQLcU4zQArwuM5iNtBWI7GOZFhtiXKCPLWFi22wSnMEsusUNygS/co98bNG8N54Y+BCos8/s302ygyOOPHlXEGQOsUaCo7MHTxL5rF+LNUrKkf/VhH7sSDI6y4gpgtQAnDNvQ0kjNs8UuWnRA928HNEAMvyNTrZX/ArUoDVldYhYDjVrbzUO/CIJMSy2CYTMQLA46/WzyR/tmlLpX7A1Xu3KC5SSGbPxnuzTg+anonOrJZNW3B9tF4CK6wX7w18xY6iSVN0WdvEOUXLAOfhnRgUn4S8Hx6/bl8jME9is5mqMRAkvY4moYXL2ZV0LkRshyJKLBTuGLYhqm9nqZcyDzg3gf1BfFEWlY5NZlrHnDyl5UuQRmoHIrr55FU9SJp4TEf+11UY0G9ZEy8q9CSp4YKe1YJ+AkzKcx1LPSwoIaq4wpPpj0KWlXqJiY4Jw4kO1XuywXewre6Yk0CiIR9XvBHxHs=
